#!/bin/bash

partition="$1"

datetime=`awk -F\- '{print $2}' version/build_datetime.h`

display_version=`awk -F\" '/BUILD_AP_VER/{print $2}' version/build_version.h`

if [ "$TARGET_BUILD_VARIANT" = "user" ]; then
    IMS_DISPLAY_ID=$BUILD_NUMBER.$display_version.$datetime
else
    IMS_DISPLAY_ID=$BUILD_NUMBER.$display_version-userdebug.$datetime
fi

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <partition>" 1>&2
  exit 1
fi

echo "# begin common build properties"
echo "# autogenerated by $0"

echo "ro.vendor.build.software.version=$IMS_DISPLAY_ID"
echo "ro.${partition}.build.date=`$DATE`"
echo "ro.${partition}.build.date.utc=`$DATE +%s`"
echo "ro.${partition}.build.fingerprint=$BUILD_FINGERPRINT"
echo "ro.${partition}.build.id=$BUILD_ID"
echo "ro.${partition}.build.tags=$BUILD_VERSION_TAGS"
echo "ro.${partition}.build.type=$TARGET_BUILD_TYPE"
echo "ro.${partition}.build.version.incremental=$BUILD_NUMBER"
echo "ro.${partition}.build.version.release=$PLATFORM_VERSION_LAST_STABLE"
echo "ro.${partition}.build.version.release_or_codename=$PLATFORM_VERSION"
echo "ro.${partition}.build.version.sdk=$PLATFORM_SDK_VERSION"

echo "ro.product.${partition}.brand=$PRODUCT_BRAND"
echo "ro.product.${partition}.manufacturer=$PRODUCT_MANUFACTURER"
echo "ro.product.${partition}.model=$PRODUCT_MODEL"

if [ -n "$OVERRIDE_TARGET_PRODUCT" ] ; then
     echo "ro.product.${partition}.name=$OVERRIDE_TARGET_PRODUCT"
     echo "ro.product.${partition}.device=$OVERRIDE_TARGET_DEVICE"
else
     echo "ro.product.${partition}.name=$PRODUCT_NAME"
     echo "ro.product.${partition}.device=$PRODUCT_DEVICE"
fi

echo "# end common build properties"
